env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"
    gh_token: "ENCRYPTED[b9455bd3688144a717e82c52d90608feb44db92bd1ad6675072685da57663b03f537e1f798e4dec1a1f46d0bea9064a3]"
    ssh_pass: "ENCRYPTED[d9ee4a45335c3c59aa93dc517d6a39b2c8bac7406370da5ff7e9728706358edbf9d979a8a5929fba9cb12bb145b66fe1]"

task:
    name: aosp
    timeout_in: 260m
    container:
      image: aarunalr/aosp-build
      cpu: 8
      memory: 32G
    download_ccache_background_script: # To download ccache in background
      - bash download_ccache # Ccache download script
    sync_script:
      - bash sync
    build_script:
      - bash build vendor sfg
    upload_ccache_script: # Upload ccache to cloud foreground
      - bash upload_ccache sfg aospa
